[phases.setup]
nixPkgs = [
  "nodejs",
  "glib",
  "nss",
  "nspr",
  "atk",
  "cups",
  "dbus",
  "libdrm",
  "libatasmart",
  "libxkbcommon",
  "pango",
  "cairo",
  "alsa-lib",
  "gtk3",
  "desktop-file-utils",
  "gdk-pixbuf",
  "glib-networking",
  "hicolor-icon-theme",
  "shared-mime-info",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXcursor",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXi",
  "xorg.libXrandr",
  "xorg.libXrender",
  "xorg.libXScrnSaver",
  "xorg.libXtst",
  "xorg.pciutils",
  "xorg.libxkbfile",
  "xorg.libXxf86vm",
  "mesa",
  "fontconfig",
  "expat"
]